import http from 'node:http';
import { mkdirSync, existsSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import { createCipheriv, createDecipheriv, createHash, createHmac, randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
import { join } from 'node:path';

const port = Number(process.env.SATURNITY_PORT || 8787);
const dataDir = process.env.SATURNITY_DATA_DIR || join(process.cwd(), '..', '..', 'saturnity-data');
const origin = process.env.SATURNITY_PUBLIC_ORIGIN || 'https://saturnity.site';
const allowedOrigins = new Set((process.env.SATURNITY_ALLOWED_ORIGINS || `${origin},https://preview.saturnity.site,https://fool.saturnity.site`).split(',').map(value => value.trim()).filter(Boolean));
const masterKey = Buffer.from(process.env.SATURNITY_MASTER_KEY || '', 'base64');
const setupToken = process.env.SATURNITY_SETUP_TOKEN || '';
if (masterKey.length !== 32) throw new Error('SATURNITY_MASTER_KEY must be a 32-byte base64 value. Run initialize-backend.ps1 first.');
if (setupToken.length < 32) throw new Error('SATURNITY_SETUP_TOKEN is missing or too short. Run initialize-backend.ps1 first.');
mkdirSync(dataDir, { recursive: true });
const db = new DatabaseSync(join(dataDir, 'saturnity.sqlite'));
db.exec(`PRAGMA journal_mode = WAL; PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, username TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS vault_snapshots (user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, revision INTEGER NOT NULL, cipher BLOB NOT NULL, iv BLOB NOT NULL, tag BLOB NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS integration_configs (user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, integration TEXT NOT NULL, label TEXT NOT NULL, cipher BLOB NOT NULL, iv BLOB NOT NULL, tag BLOB NOT NULL, updated_at INTEGER NOT NULL, PRIMARY KEY(user_id, integration));
CREATE TABLE IF NOT EXISTS job_monitor_jobs (user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, job_id TEXT NOT NULL, kind TEXT, status TEXT, total_amount INTEGER, success_amount INTEGER, fail_amount INTEGER, skip_amount INTEGER, refunded_amount INTEGER, note TEXT, priority INTEGER, created_at_text TEXT, last_checked_at INTEGER NOT NULL, PRIMARY KEY(user_id, job_id));
CREATE TABLE IF NOT EXISTS private_scripts (id TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, name TEXT NOT NULL, cipher BLOB NOT NULL, iv BLOB NOT NULL, tag BLOB NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS private_script_tokens (id TEXT PRIMARY KEY, script_id TEXT NOT NULL REFERENCES private_scripts(id) ON DELETE CASCADE, token_hash TEXT NOT NULL UNIQUE, token_cipher BLOB, token_iv BLOB, token_tag BLOB, created_at INTEGER NOT NULL, last_used_at INTEGER, revoked_at INTEGER);`);
db.exec(`CREATE TABLE IF NOT EXISTS public_tool_config (owner_user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, pin_hash TEXT NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS public_tool_sessions (token_hash TEXT PRIMARY KEY, expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS fool_shared_scripts (script_id TEXT PRIMARY KEY REFERENCES private_scripts(id) ON DELETE CASCADE, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_id TEXT NOT NULL REFERENCES private_script_tokens(id) ON DELETE CASCADE, shared_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS fool_public_scripts (id TEXT PRIMARY KEY, name TEXT NOT NULL, cipher BLOB NOT NULL, iv BLOB NOT NULL, tag BLOB NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS fool_public_script_tokens (script_id TEXT PRIMARY KEY REFERENCES fool_public_scripts(id) ON DELETE CASCADE, token_hash TEXT NOT NULL UNIQUE, token_cipher BLOB NOT NULL, token_iv BLOB NOT NULL, token_tag BLOB NOT NULL, created_at INTEGER NOT NULL);`);
const scriptTokenColumns = db.prepare('PRAGMA table_info(private_script_tokens)').all().map(column => column.name);
if (!scriptTokenColumns.includes('token_cipher')) db.exec('ALTER TABLE private_script_tokens ADD COLUMN token_cipher BLOB');
if (!scriptTokenColumns.includes('token_iv')) db.exec('ALTER TABLE private_script_tokens ADD COLUMN token_iv BLOB');
if (!scriptTokenColumns.includes('token_tag')) db.exec('ALTER TABLE private_script_tokens ADD COLUMN token_tag BLOB');
const scriptColumns = db.prepare('PRAGMA table_info(private_scripts)').all().map(column => column.name);
if (!scriptColumns.includes('storage_synced_at')) db.exec('ALTER TABLE private_scripts ADD COLUMN storage_synced_at INTEGER');
const now = () => Date.now();
const hashToken = value => createHash('sha256').update(value).digest('hex');
const passwordHash = password => { const salt = randomBytes(16); return `${salt.toString('base64')}:${scryptSync(password, salt, 64).toString('base64')}`; };
const passwordMatches = (password, saved) => { const [salt64, hash64] = String(saved).split(':'); const actual = scryptSync(password, Buffer.from(salt64, 'base64'), 64); const expected = Buffer.from(hash64, 'base64'); return actual.length === expected.length && timingSafeEqual(actual, expected); };
const encrypt = text => { const iv = randomBytes(12); const cipher = createCipheriv('aes-256-gcm', masterKey, iv); const body = Buffer.concat([cipher.update(text, 'utf8'), cipher.final()]); return { body, iv, tag: cipher.getAuthTag() }; };
const decrypt = row => { const cipher = createDecipheriv('aes-256-gcm', masterKey, Buffer.from(row.iv)); cipher.setAuthTag(Buffer.from(row.tag)); return Buffer.concat([cipher.update(Buffer.from(row.cipher)), cipher.final()]).toString('utf8'); };
const maskSecret = value => value.length < 9 ? 'configured' : `${value.slice(0, 4)}••••${value.slice(-4)}`;
const highspecBase = 'https://api.highspec.gg/api/v1';
const monitorConfig = user => { const row = db.prepare('SELECT * FROM integration_configs WHERE user_id=? AND integration=?').get(user.id, 'job-monitor'); if (!row) throw new Error('Save a provider API key in Private Controls first.'); return { label: row.label, ...JSON.parse(decrypt(row)) }; };
const providerRead = async (user, path) => { const config = monitorConfig(user); const response = await fetch(`${highspecBase}${path}`, { headers: { 'X-API-Key': config.apiKey }, signal: AbortSignal.timeout(12_000) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || payload.error || `Provider request failed (${response.status})`); return payload.data || payload; };
const integrationRow = (user, integration) => db.prepare('SELECT * FROM integration_configs WHERE user_id=? AND integration=?').get(user.id, integration);
const nevaConfig = user => { const row = integrationRow(user, 'neva-storage'); if (!row) throw new Error('Save Neva Storage settings first.'); return { ...JSON.parse(decrypt(row)), updatedAt: row.updated_at }; };
const hmac = (key, value, encoding) => createHmac('sha256', key).update(value, 'utf8').digest(encoding);
const s3Timestamp = date => `${date.getUTCFullYear()}${String(date.getUTCMonth() + 1).padStart(2, '0')}${String(date.getUTCDate()).padStart(2, '0')}T${String(date.getUTCHours()).padStart(2, '0')}${String(date.getUTCMinutes()).padStart(2, '0')}${String(date.getUTCSeconds()).padStart(2, '0')}Z`;
const s3Path = (bucket, key = '') => `/${[bucket, ...String(key).split('/').filter(Boolean)].map(encodeURIComponent).join('/')}`;
const s3SignedRequest = async (config, method, key = '', { body = '', query = '', contentType = '' } = {}) => {
  const endpoint = new URL(config.endpoint);
  const date = new Date(), amzDate = s3Timestamp(date), day = amzDate.slice(0, 8), region = config.region || 'us-east-1', service = 's3';
  const canonicalUri = s3Path(config.bucket, key), canonicalQuery = query, payloadHash = createHash('sha256').update(body).digest('hex');
  const typeHeader = contentType ? `content-type:${contentType}\n` : '', signedHeaders = contentType ? 'content-type;host;x-amz-content-sha256;x-amz-date' : 'host;x-amz-content-sha256;x-amz-date';
  const canonicalHeaders = `${typeHeader}host:${endpoint.host}\nx-amz-content-sha256:${payloadHash}\nx-amz-date:${amzDate}\n`;
  const scope = `${day}/${region}/${service}/aws4_request`, canonicalRequest = `GET\n${canonicalUri}\n${canonicalQuery}\n${canonicalHeaders}\n${signedHeaders}\n${payloadHash}`;
  const request = `${method}\n${canonicalUri}\n${canonicalQuery}\n${canonicalHeaders}\n${signedHeaders}\n${payloadHash}`, stringToSign = `AWS4-HMAC-SHA256\n${amzDate}\n${scope}\n${createHash('sha256').update(request).digest('hex')}`;
  const dateKey = hmac(`AWS4${config.secretKey}`, day), regionKey = hmac(dateKey, region), serviceKey = hmac(regionKey, service), signingKey = hmac(serviceKey, 'aws4_request');
  const signature = hmac(signingKey, stringToSign, 'hex'), authorization = `AWS4-HMAC-SHA256 Credential=${config.accessKey}/${scope}, SignedHeaders=${signedHeaders}, Signature=${signature}`;
  const headers = { Authorization: authorization, 'x-amz-content-sha256': payloadHash, 'x-amz-date': amzDate }; if (contentType) headers['Content-Type'] = contentType;
  return fetch(`${endpoint.origin}${canonicalUri}${query ? `?${query}` : ''}`, { method, headers, body: body || undefined, signal: AbortSignal.timeout(12_000) });
};
const nevaBucketTest = async user => {
  const config = nevaConfig(user), response = await s3SignedRequest(config, 'GET', '', { query: 'list-type=2&max-keys=1' });
  if (!response.ok) throw new Error(response.status === 404 ? `Neva could not find the bucket “${config.bucket}”. Create it or correct its name.` : response.status === 403 ? 'Neva rejected the access key or bucket permission.' : `Neva bucket check failed (${response.status}).`);
  return { ok: true, bucket: config.bucket, endpoint: config.endpoint };
};
const scriptObjectKey = (user, scriptId) => `the-fool/${user.id}/${scriptId}.lua`;
const syncScriptToNeva = async (user, scriptId, content) => { const config = nevaConfig(user), response = await s3SignedRequest(config, 'PUT', scriptObjectKey(user, scriptId), { body: content, contentType: 'text/plain; charset=utf-8' }); if (!response.ok) throw new Error(`Neva script upload failed (${response.status}).`); };
const removeScriptFromNeva = async (user, scriptId) => { const response = await s3SignedRequest(nevaConfig(user), 'DELETE', scriptObjectKey(user, scriptId)); if (!response.ok && response.status !== 404) throw new Error(`Neva script removal failed (${response.status}).`); };
const nevaSignedDownload = (config, key, expires = 300) => { const endpoint = new URL(config.endpoint), date = new Date(), amzDate = s3Timestamp(date), day = amzDate.slice(0, 8), region = config.region || 'us-east-1', service = 's3', scope = `${day}/${region}/${service}/aws4_request`, canonicalUri = s3Path(config.bucket, key), credential = `${config.accessKey}/${scope}`, values = { 'X-Amz-Algorithm': 'AWS4-HMAC-SHA256', 'X-Amz-Credential': credential, 'X-Amz-Date': amzDate, 'X-Amz-Expires': String(expires), 'X-Amz-SignedHeaders': 'host' }, canonicalQuery = Object.entries(values).map(([key,value])=>[encodeURIComponent(key),encodeURIComponent(value)]).sort(([a],[b])=>a.localeCompare(b)).map(([key,value])=>`${key}=${value}`).join('&'), canonicalRequest = `GET\n${canonicalUri}\n${canonicalQuery}\nhost:${endpoint.host}\n\nhost\nUNSIGNED-PAYLOAD`, stringToSign = `AWS4-HMAC-SHA256\n${amzDate}\n${scope}\n${createHash('sha256').update(canonicalRequest).digest('hex')}`, signing = hmac(hmac(hmac(hmac(`AWS4${config.secretKey}`, day), region), service), 'aws4_request'), signature = hmac(signing, stringToSign, 'hex'); return `${endpoint.origin}${canonicalUri}?${canonicalQuery}&X-Amz-Signature=${signature}`; };
const cleanJob = (raw, fallbackId) => ({ id: String(raw.id || fallbackId), kind: raw.type === 'FACE_SCAN' ? 'FACE SCAN' : (raw.kind || raw.job_type || 'CAPTCHA'), status: ['PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'].includes(raw.status) ? raw.status : 'PENDING', totalAmount: Number(raw.total_amount || raw.total_accounts || 0), successAmount: Number(raw.success_amount || 0), failAmount: Number(raw.fail_amount || 0), skipAmount: Number(raw.skip_amount || 0), refundedAmount: Number(raw.refunded_amount || 0), note: String(raw.note || '').slice(0, 180), priority: Boolean(raw.priority), createdAt: String(raw.created_at || '') });
const saveJob = (user, job) => db.prepare('INSERT INTO job_monitor_jobs (user_id,job_id,kind,status,total_amount,success_amount,fail_amount,skip_amount,refunded_amount,note,priority,created_at_text,last_checked_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id,job_id) DO UPDATE SET kind=excluded.kind,status=excluded.status,total_amount=excluded.total_amount,success_amount=excluded.success_amount,fail_amount=excluded.fail_amount,skip_amount=excluded.skip_amount,refunded_amount=excluded.refunded_amount,note=excluded.note,priority=excluded.priority,created_at_text=excluded.created_at_text,last_checked_at=excluded.last_checked_at').run(user.id, job.id, job.kind, job.status, job.totalAmount, job.successAmount, job.failAmount, job.skipAmount, job.refundedAmount, job.note, job.priority ? 1 : 0, job.createdAt, now());
const storedJobs = user => db.prepare('SELECT job_id AS id,kind,status,total_amount AS totalAmount,success_amount AS successAmount,fail_amount AS failAmount,skip_amount AS skipAmount,refunded_amount AS refundedAmount,note,priority,created_at_text AS createdAt,last_checked_at AS lastCheckedAt FROM job_monitor_jobs WHERE user_id=? ORDER BY last_checked_at DESC').all(user.id);
const scriptName = value => { const name = String(value || '').trim(); if (!/^[A-Za-z0-9._-]{1,100}\.lua$/i.test(name)) throw new Error('Use a .lua file name containing letters, numbers, dots, dashes, or underscores.'); return name; };
const scriptList = user => db.prepare('SELECT s.id,s.name,s.created_at AS createdAt,s.updated_at AS updatedAt,s.storage_synced_at AS storageSyncedAt,COUNT(t.id) AS tokenCount,EXISTS(SELECT 1 FROM fool_shared_scripts fs JOIN private_script_tokens fst ON fst.id=fs.token_id AND fst.revoked_at IS NULL WHERE fs.script_id=s.id AND fs.user_id=s.user_id) AS foolShared FROM private_scripts s LEFT JOIN private_script_tokens t ON t.script_id=s.id AND t.revoked_at IS NULL WHERE s.user_id=? GROUP BY s.id ORDER BY s.updated_at DESC').all(user.id);
const userScript = (user, id) => db.prepare('SELECT * FROM private_scripts WHERE id=? AND user_id=?').get(id, user.id);
const json = (res, code, payload, headers = {}) => { res.writeHead(code, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', ...headers }); res.end(JSON.stringify(payload)); };
const text = (res, code, body, headers = {}) => { res.writeHead(code, { 'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'no-store', 'X-Content-Type-Options': 'nosniff', ...headers }); res.end(body); };
const cookies = req => Object.fromEntries((req.headers.cookie || '').split(';').map(item => item.trim().split(/=(.*)/s)).filter(([key]) => key).map(([key, value]) => [key, decodeURIComponent(value || '')]));
const readBody = req => new Promise((resolve, reject) => { let size = 0, data = ''; req.on('data', chunk => { size += chunk.length; if (size > 20 * 1024 * 1024) { reject(new Error('Request too large')); req.destroy(); } else data += chunk; }); req.on('end', () => { try { resolve(data ? JSON.parse(data) : {}); } catch { reject(new Error('Invalid JSON')); } }); req.on('error', reject); });
const ownerExists = () => !!db.prepare('SELECT 1 FROM users LIMIT 1').get();
const requireOrigin = req => !['POST', 'PUT', 'PATCH', 'DELETE'].includes(req.method) || allowedOrigins.has(req.headers.origin);
const sessionUser = req => { const token = cookies(req).saturnity_session; if (!token) return null; const row = db.prepare('SELECT u.id,u.username FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').get(hashToken(token), now()); return row || null; };
const requireUser = (req, res) => { const user = sessionUser(req); if (!user) { json(res, 401, { error: 'Authentication required' }); return null; } return user; };
const publicToolsUnlocked = req => { const token = cookies(req).fool_tools_session; if (!token) return false; return !!db.prepare('SELECT 1 FROM public_tool_sessions WHERE token_hash=? AND expires_at>?').get(hashToken(token), now()); };
const limits = new Map();
// The service is bound to localhost and Caddy is the only public proxy. Use its
// forwarded client address so one visitor cannot consume every user's budget.
const clientAddress = req => String(req.headers['x-forwarded-for'] || '').split(',')[0].trim() || req.socket.remoteAddress || 'unknown';
const rateAllowed = req => { const key = clientAddress(req), max = req.url.startsWith('/api/script-raw/') || req.url.startsWith('/api/fool-public-raw/') ? 180 : 30; const slot = limits.get(`${max}:${key}`) || { n: 0, reset: now() + 60_000 }; if (now() > slot.reset) { slot.n = 0; slot.reset = now() + 60_000; } slot.n++; limits.set(`${max}:${key}`, slot); return slot.n <= max; };
const server = http.createServer(async (req, res) => {
  try {
    if (!rateAllowed(req)) return json(res, 429, { error: 'Too many requests' });
    if (!requireOrigin(req)) return json(res, 403, { error: 'Invalid request origin' });
    const url = new URL(req.url, origin);
    if (req.method === 'GET' && url.pathname === '/api/health') return json(res, 200, { ok: true, needsSetup: !ownerExists() });
    if (req.method === 'GET' && url.pathname.startsWith('/api/fool-public-raw/')) { const scriptId = decodeURIComponent(url.pathname.slice('/api/fool-public-raw/'.length)), access = String(url.searchParams.get('access') || ''); if (!/^[A-Za-z0-9_-]{8,100}$/.test(scriptId) || access.length < 32) return text(res, 403, 'Forbidden'); const script = db.prepare('SELECT s.cipher,s.iv,s.tag FROM fool_public_script_tokens t JOIN fool_public_scripts s ON s.id=t.script_id WHERE t.script_id=? AND t.token_hash=?').get(scriptId, hashToken(access)); return script ? text(res, 200, decrypt(script)) : text(res, 403, 'Forbidden'); }
    if (req.method === 'GET' && url.pathname.startsWith('/api/script-raw/')) { const scriptId = decodeURIComponent(url.pathname.slice('/api/script-raw/'.length)); const access = String(url.searchParams.get('access') || ''); if (!/^[A-Za-z0-9_-]{8,100}$/.test(scriptId) || access.length < 32) return text(res, 403, 'Forbidden'); const token = db.prepare('SELECT t.id,s.id AS script_id,s.user_id,s.storage_synced_at,s.cipher,s.iv,s.tag FROM private_script_tokens t JOIN private_scripts s ON s.id=t.script_id WHERE t.script_id=? AND t.token_hash=? AND t.revoked_at IS NULL').get(scriptId, hashToken(access)); if (!token) return text(res, 403, 'Forbidden'); db.prepare('UPDATE private_script_tokens SET last_used_at=? WHERE id=?').run(now(), token.id); if (token.storage_synced_at) { const owner = { id: token.user_id }; try { return res.writeHead(302, { Location: nevaSignedDownload(nevaConfig(owner), scriptObjectKey(owner, token.script_id)), 'Cache-Control': 'private, no-store', 'X-Content-Type-Options': 'nosniff' }).end(); } catch { /* Preserve existing links if storage is temporarily unavailable. */ } } return text(res, 200, decrypt(token)); }
    if (req.method === 'POST' && url.pathname === '/api/setup') {
      if (ownerExists()) return json(res, 409, { error: 'Owner account already exists' });
      const body = await readBody(req); const username = String(body.username || '').trim(); const password = String(body.password || '');
      const suppliedToken = Buffer.from(String(body.setupToken || ''));
      const expectedToken = Buffer.from(setupToken);
      if (suppliedToken.length !== expectedToken.length || !timingSafeEqual(suppliedToken, expectedToken)) return json(res, 403, { error: 'Invalid setup token' });
      if (!/^[a-zA-Z0-9_-]{3,32}$/.test(username) || password.length < 14) return json(res, 400, { error: 'Use a 3–32 character username and a password of at least 14 characters' });
      db.prepare('INSERT INTO users (username,password_hash,created_at) VALUES (?,?,?)').run(username, passwordHash(password), now());
      return json(res, 201, { ok: true });
    }
    if (req.method === 'POST' && url.pathname === '/api/login') {
      const body = await readBody(req); const user = db.prepare('SELECT * FROM users WHERE username=?').get(String(body.username || '').trim());
      if (!user || !passwordMatches(String(body.password || ''), user.password_hash)) return json(res, 401, { error: 'Invalid username or password' });
      const token = randomBytes(32).toString('base64url'); const expires = now() + 30 * 24 * 60 * 60 * 1000;
      db.prepare('INSERT INTO sessions (token_hash,user_id,expires_at,created_at) VALUES (?,?,?,?)').run(hashToken(token), user.id, expires, now());
      return json(res, 200, { ok: true, username: user.username }, { 'Set-Cookie': `saturnity_session=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=2592000` });
    }
    if (req.method === 'POST' && url.pathname === '/api/logout') { const token = cookies(req).saturnity_session; if (token) db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hashToken(token)); return json(res, 200, { ok: true }, { 'Set-Cookie': 'saturnity_session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0' }); }
    if (req.method === 'GET' && url.pathname === '/api/me') { const user = requireUser(req, res); if (!user) return; return json(res, 200, { username: user.username }); }
    if (req.method === 'GET' && url.pathname === '/api/fool-public/status') { const config = db.prepare('SELECT 1 FROM public_tool_config LIMIT 1').get(); return json(res, 200, { configured: !!config, unlocked: publicToolsUnlocked(req) }); }
    if (req.method === 'PUT' && url.pathname === '/api/fool-public/config') { const user = requireUser(req, res); if (!user) return; const pin = String((await readBody(req)).pin || ''); if (!/^\d{6,12}$/.test(pin)) return json(res, 400, { error: 'Use a numeric PIN with 6 to 12 digits.' }); db.prepare('INSERT INTO public_tool_config (owner_user_id,pin_hash,updated_at) VALUES (?,?,?) ON CONFLICT(owner_user_id) DO UPDATE SET pin_hash=excluded.pin_hash,updated_at=excluded.updated_at').run(user.id, passwordHash(pin), now()); return json(res, 200, { configured: true }); }
    if (req.method === 'POST' && url.pathname === '/api/fool-public/unlock') { const config = db.prepare('SELECT * FROM public_tool_config LIMIT 1').get(), pin = String((await readBody(req)).pin || ''); if (!config || !passwordMatches(pin, config.pin_hash)) return json(res, 401, { error: 'Invalid access PIN.' }); const token = randomBytes(32).toString('base64url'), expires = now() + 7 * 24 * 60 * 60 * 1000; db.prepare('INSERT INTO public_tool_sessions (token_hash,expires_at,created_at) VALUES (?,?,?)').run(hashToken(token), expires, now()); return json(res, 200, { ok: true }, { 'Set-Cookie': `fool_tools_session=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=604800` }); }
    if (req.method === 'POST' && url.pathname === '/api/fool-public/logout') { const token = cookies(req).fool_tools_session; if (token) db.prepare('DELETE FROM public_tool_sessions WHERE token_hash=?').run(hashToken(token)); return json(res, 200, { ok: true }, { 'Set-Cookie': 'fool_tools_session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0' }); }
    if (req.method === 'GET' && url.pathname === '/api/fool-public/scripts') { if (!publicToolsUnlocked(req)) return json(res, 401, { error: 'Shared tools access is required.' }); const ownerScripts = db.prepare('SELECT s.id,s.name,s.updated_at AS updatedAt,t.token_cipher,t.token_iv,t.token_tag FROM fool_shared_scripts fs JOIN private_scripts s ON s.id=fs.script_id JOIN private_script_tokens t ON t.id=fs.token_id AND t.revoked_at IS NULL ORDER BY fs.shared_at DESC').all().map(script => ({ id: script.id, name: script.name, updatedAt: script.updatedAt, source: 'owner', rawUrl: `${origin}/api/script-raw/${encodeURIComponent(script.id)}?access=${encodeURIComponent(decrypt({ cipher: script.token_cipher, iv: script.token_iv, tag: script.token_tag }))}` })); const memberScripts = db.prepare('SELECT s.id,s.name,s.updated_at AS updatedAt,t.token_cipher,t.token_iv,t.token_tag FROM fool_public_scripts s JOIN fool_public_script_tokens t ON t.script_id=s.id ORDER BY s.created_at DESC').all().map(script => ({ id: script.id, name: script.name, updatedAt: script.updatedAt, source: 'member', rawUrl: `${origin}/api/fool-public-raw/${encodeURIComponent(script.id)}?access=${encodeURIComponent(decrypt({ cipher: script.token_cipher, iv: script.token_iv, tag: script.token_tag }))}` })); return json(res, 200, { scripts: [...ownerScripts, ...memberScripts] }); }
    if (req.method === 'POST' && url.pathname === '/api/fool-public/scripts') { if (!publicToolsUnlocked(req)) return json(res, 401, { error: 'Shared tools access is required.' }); const body = await readBody(req), name = scriptName(body.name), content = String(body.content || ''); if (!content.trim()) return json(res, 400, { error: 'Add script content first.' }); if (content.length > 500_000) return json(res, 400, { error: 'Script exceeds the 500 KB limit.' }); const id = randomBytes(12).toString('base64url'), access = randomBytes(32).toString('base64url'), encrypted = encrypt(content), token = encrypt(access), savedAt = now(); db.prepare('INSERT INTO fool_public_scripts (id,name,cipher,iv,tag,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').run(id, name, encrypted.body, encrypted.iv, encrypted.tag, savedAt, savedAt); db.prepare('INSERT INTO fool_public_script_tokens (script_id,token_hash,token_cipher,token_iv,token_tag,created_at) VALUES (?,?,?,?,?,?)').run(id, hashToken(access), token.body, token.iv, token.tag, savedAt); return json(res, 201, { script: { id, name, updatedAt: savedAt, source: 'member', rawUrl: `${origin}/api/fool-public-raw/${encodeURIComponent(id)}?access=${encodeURIComponent(access)}` } }); }
    if (req.method === 'GET' && /^\/api\/fool-public\/scripts\/[^/]+$/.test(url.pathname)) { if (!publicToolsUnlocked(req)) return json(res, 401, { error: 'Shared tools access is required.' }); const scriptId = decodeURIComponent(url.pathname.slice('/api/fool-public/scripts/'.length)); const script = db.prepare('SELECT id,name,cipher,iv,tag,updated_at AS updatedAt FROM fool_public_scripts WHERE id=?').get(scriptId); return script ? json(res, 200, { script: { id: script.id, name: script.name, content: decrypt(script), source: 'member', updatedAt: script.updatedAt } }) : json(res, 404, { error: 'This shared script is owner-managed and can only be edited in the private repository.' }); }
    if (req.method === 'PUT' && /^\/api\/fool-public\/scripts\/[^/]+$/.test(url.pathname)) { if (!publicToolsUnlocked(req)) return json(res, 401, { error: 'Shared tools access is required.' }); const scriptId = decodeURIComponent(url.pathname.slice('/api/fool-public/scripts/'.length)), body = await readBody(req), name = scriptName(body.name), content = String(body.content || ''); if (!content.trim()) return json(res, 400, { error: 'Add script content first.' }); if (content.length > 500_000) return json(res, 400, { error: 'Script exceeds the 500 KB limit.' }); const encrypted = encrypt(content), updatedAt = now(), changed = db.prepare('UPDATE fool_public_scripts SET name=?,cipher=?,iv=?,tag=?,updated_at=? WHERE id=?').run(name, encrypted.body, encrypted.iv, encrypted.tag, updatedAt, scriptId); return changed.changes ? json(res, 200, { script: { id: scriptId, name, updatedAt, source: 'member' } }) : json(res, 404, { error: 'Only member-added scripts can be edited here.' }); }
    if (req.method === 'DELETE' && /^\/api\/fool-public\/scripts\/[^/]+$/.test(url.pathname)) { if (!publicToolsUnlocked(req)) return json(res, 401, { error: 'Shared tools access is required.' }); const scriptId = decodeURIComponent(url.pathname.slice('/api/fool-public/scripts/'.length)); const removed = db.prepare('DELETE FROM fool_public_scripts WHERE id=?').run(scriptId); return removed.changes ? json(res, 200, { ok: true }) : json(res, 404, { error: 'Only member-added scripts can be deleted here.' }); }
    if (url.pathname === '/api/integrations/job-monitor' && req.method === 'GET') { const user = requireUser(req, res); if (!user) return; const row = db.prepare('SELECT * FROM integration_configs WHERE user_id=? AND integration=?').get(user.id, 'job-monitor'); if (!row) return json(res, 200, { configured: false }); const secret = JSON.parse(decrypt(row)); return json(res, 200, { configured: true, label: row.label, keyHint: maskSecret(String(secret.apiKey || '')), updatedAt: row.updated_at }); }
    if (url.pathname === '/api/integrations/job-monitor' && req.method === 'PUT') { const user = requireUser(req, res); if (!user) return; const body = await readBody(req); const label = String(body.label || 'Provider log monitor').trim().slice(0, 60) || 'Provider log monitor'; const apiKey = String(body.apiKey || '').trim(); if (apiKey.length < 8 || apiKey.length > 512) return json(res, 400, { error: 'Enter a valid API key.' }); const encrypted = encrypt(JSON.stringify({ apiKey })); db.prepare('INSERT INTO integration_configs (user_id,integration,label,cipher,iv,tag,updated_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(user_id,integration) DO UPDATE SET label=excluded.label,cipher=excluded.cipher,iv=excluded.iv,tag=excluded.tag,updated_at=excluded.updated_at').run(user.id, 'job-monitor', label, encrypted.body, encrypted.iv, encrypted.tag, now()); return json(res, 200, { configured: true, label, keyHint: maskSecret(apiKey), updatedAt: now() }); }
    if (url.pathname === '/api/integrations/job-monitor' && req.method === 'DELETE') { const user = requireUser(req, res); if (!user) return; db.prepare('DELETE FROM integration_configs WHERE user_id=? AND integration=?').run(user.id, 'job-monitor'); return json(res, 200, { configured: false }); }
    if (url.pathname === '/api/integrations/neva-storage' && req.method === 'GET') { const user = requireUser(req, res); if (!user) return; const row = integrationRow(user, 'neva-storage'); if (!row) return json(res, 200, { configured: false, bucket: 'the-fool-bucket', endpoint: 'https://s3.nevaobjects.id', region: 'us-east-1' }); const secret = JSON.parse(decrypt(row)); return json(res, 200, { configured: true, bucket: secret.bucket, endpoint: secret.endpoint, region: secret.region, accessKeyHint: maskSecret(String(secret.accessKey || '')), secretKeyHint: maskSecret(String(secret.secretKey || '')), updatedAt: row.updated_at }); }
    if (url.pathname === '/api/integrations/neva-storage' && req.method === 'PUT') { const user = requireUser(req, res); if (!user) return; const body = await readBody(req); const bucket = String(body.bucket || '').trim(), endpoint = String(body.endpoint || 'https://s3.nevaobjects.id').trim(), region = String(body.region || 'us-east-1').trim(), accessKey = String(body.accessKey || '').trim(), secretKey = String(body.secretKey || '').trim(); if (!/^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$/i.test(bucket)) return json(res, 400, { error: 'Enter a valid bucket name.' }); let parsed; try { parsed = new URL(endpoint); } catch { return json(res, 400, { error: 'Enter a valid HTTPS endpoint.' }); } if (parsed.protocol !== 'https:' || parsed.pathname !== '/' || parsed.search || parsed.hash) return json(res, 400, { error: 'Use an HTTPS storage endpoint without a path.' }); if (!/^[a-z0-9-]{2,40}$/i.test(region) || accessKey.length < 8 || accessKey.length > 256 || secretKey.length < 16 || secretKey.length > 512) return json(res, 400, { error: 'Enter valid access and secret keys.' }); const encrypted = encrypt(JSON.stringify({ bucket, endpoint: parsed.origin, region, accessKey, secretKey })); db.prepare('INSERT INTO integration_configs (user_id,integration,label,cipher,iv,tag,updated_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(user_id,integration) DO UPDATE SET label=excluded.label,cipher=excluded.cipher,iv=excluded.iv,tag=excluded.tag,updated_at=excluded.updated_at').run(user.id, 'neva-storage', 'Neva Object Storage', encrypted.body, encrypted.iv, encrypted.tag, now()); return json(res, 200, { configured: true, bucket, endpoint: parsed.origin, region, accessKeyHint: maskSecret(accessKey), secretKeyHint: maskSecret(secretKey), updatedAt: now() }); }
    if (url.pathname === '/api/integrations/neva-storage/test' && req.method === 'POST') { const user = requireUser(req, res); if (!user) return; try { return json(res, 200, await nevaBucketTest(user)); } catch (error) { console.error(`[neva-storage] ${error.message}`); return json(res, 502, { error: error.message === 'fetch failed' ? 'Could not reach the Neva storage endpoint.' : error.message }); } }
    if (url.pathname === '/api/integrations/neva-storage' && req.method === 'DELETE') { const user = requireUser(req, res); if (!user) return; db.prepare('DELETE FROM integration_configs WHERE user_id=? AND integration=?').run(user.id, 'neva-storage'); return json(res, 200, { configured: false }); }
    if (url.pathname === '/api/private-scripts' && req.method === 'GET') { const user = requireUser(req, res); if (!user) return; return json(res, 200, { scripts: scriptList(user) }); }
    if (url.pathname === '/api/private-scripts' && req.method === 'POST') { const user = requireUser(req, res); if (!user) return; const body = await readBody(req), name = scriptName(body.name), content = String(body.content || ''); if (content.length > 500_000) return json(res, 400, { error: 'Script exceeds the 500 KB limit.' }); const id = randomBytes(12).toString('base64url'), mirrored = !!integrationRow(user, 'neva-storage'); if (mirrored) await syncScriptToNeva(user, id, content); const encrypted = encrypt(content), savedAt = now(); db.prepare('INSERT INTO private_scripts (id,user_id,name,cipher,iv,tag,created_at,updated_at,storage_synced_at) VALUES (?,?,?,?,?,?,?,?,?)').run(id, user.id, name, encrypted.body, encrypted.iv, encrypted.tag, savedAt, savedAt, mirrored ? savedAt : null); return json(res, 201, { script: { id, name, createdAt: savedAt, updatedAt: savedAt, storageSyncedAt: mirrored ? savedAt : null, tokenCount: 0 } }); }
    if (url.pathname.startsWith('/api/private-scripts/') && url.pathname.endsWith('/fool-share') && req.method === 'POST') { const user = requireUser(req, res); if (!user) return; const scriptId = decodeURIComponent(url.pathname.slice('/api/private-scripts/'.length, -'/fool-share'.length)), script = userScript(user, scriptId); if (!script) return json(res, 404, { error: 'Script not found.' }); const shared = db.prepare('SELECT fs.token_id FROM fool_shared_scripts fs JOIN private_script_tokens t ON t.id=fs.token_id AND t.revoked_at IS NULL WHERE fs.script_id=? AND fs.user_id=?').get(scriptId, user.id); if (shared) return json(res, 200, { shared: true }); const access = randomBytes(32).toString('base64url'), tokenId = randomBytes(12).toString('base64url'), encrypted = encrypt(access); db.prepare('INSERT INTO private_script_tokens (id,script_id,token_hash,token_cipher,token_iv,token_tag,created_at) VALUES (?,?,?,?,?,?,?)').run(tokenId, scriptId, hashToken(access), encrypted.body, encrypted.iv, encrypted.tag, now()); db.prepare('INSERT INTO fool_shared_scripts (script_id,user_id,token_id,shared_at) VALUES (?,?,?,?) ON CONFLICT(script_id) DO UPDATE SET user_id=excluded.user_id,token_id=excluded.token_id,shared_at=excluded.shared_at').run(scriptId, user.id, tokenId, now()); return json(res, 201, { shared: true }); }
    if (url.pathname.startsWith('/api/private-scripts/') && url.pathname.endsWith('/fool-share') && req.method === 'DELETE') { const user = requireUser(req, res); if (!user) return; const scriptId = decodeURIComponent(url.pathname.slice('/api/private-scripts/'.length, -'/fool-share'.length)), script = userScript(user, scriptId); if (!script) return json(res, 404, { error: 'Script not found.' }); const shared = db.prepare('SELECT token_id FROM fool_shared_scripts WHERE script_id=? AND user_id=?').get(scriptId, user.id); if (shared) { db.prepare('DELETE FROM fool_shared_scripts WHERE script_id=? AND user_id=?').run(scriptId, user.id); db.prepare('UPDATE private_script_tokens SET revoked_at=? WHERE id=? AND script_id=?').run(now(), shared.token_id, scriptId); } return json(res, 200, { shared: false }); }
    if (url.pathname.startsWith('/api/private-scripts/') && url.pathname.endsWith('/tokens') && req.method === 'GET') { const user = requireUser(req, res); if (!user) return; const scriptId = decodeURIComponent(url.pathname.slice('/api/private-scripts/'.length, -'/tokens'.length)); const script = userScript(user, scriptId); if (!script) return json(res, 404, { error: 'Script not found.' }); const tokens = db.prepare('SELECT id,token_cipher,token_iv,token_tag,created_at AS createdAt,last_used_at AS lastUsedAt FROM private_script_tokens WHERE script_id=? AND revoked_at IS NULL ORDER BY created_at DESC').all(scriptId).map(token => ({ id: token.id, createdAt: token.createdAt, lastUsedAt: token.lastUsedAt, access: token.token_cipher ? decrypt({ cipher: token.token_cipher, iv: token.token_iv, tag: token.token_tag }) : null })); return json(res, 200, { tokens }); }
    if (url.pathname.startsWith('/api/private-scripts/') && url.pathname.endsWith('/tokens') && req.method === 'POST') { const user = requireUser(req, res); if (!user) return; const scriptId = decodeURIComponent(url.pathname.slice('/api/private-scripts/'.length, -'/tokens'.length)); const script = userScript(user, scriptId); if (!script) return json(res, 404, { error: 'Script not found.' }); const access = randomBytes(32).toString('base64url'), tokenId = randomBytes(12).toString('base64url'), encrypted = encrypt(access); db.prepare('INSERT INTO private_script_tokens (id,script_id,token_hash,token_cipher,token_iv,token_tag,created_at) VALUES (?,?,?,?,?,?,?)').run(tokenId, scriptId, hashToken(access), encrypted.body, encrypted.iv, encrypted.tag, now()); return json(res, 201, { tokenId, access }); }
    if (url.pathname.startsWith('/api/private-scripts/') && /\/tokens\/[^/]+$/.test(url.pathname) && req.method === 'DELETE') { const user = requireUser(req, res); if (!user) return; const [, scriptId, tokenId] = url.pathname.match(/^\/api\/private-scripts\/([^/]+)\/tokens\/([^/]+)$/).map(decodeURIComponent); const script = userScript(user, scriptId); if (!script) return json(res, 404, { error: 'Script not found.' }); db.prepare('UPDATE private_script_tokens SET revoked_at=? WHERE id=? AND script_id=?').run(now(), tokenId, scriptId); return json(res, 200, { ok: true }); }
    if (url.pathname.startsWith('/api/private-scripts/') && req.method === 'GET') { const user = requireUser(req, res); if (!user) return; const script = userScript(user, decodeURIComponent(url.pathname.slice('/api/private-scripts/'.length))); if (!script) return json(res, 404, { error: 'Script not found.' }); const foolShared = !!db.prepare('SELECT 1 FROM fool_shared_scripts fs JOIN private_script_tokens t ON t.id=fs.token_id AND t.revoked_at IS NULL WHERE fs.script_id=? AND fs.user_id=?').get(script.id, user.id); return json(res, 200, { script: { id: script.id, name: script.name, content: decrypt(script), createdAt: script.created_at, updatedAt: script.updated_at, storageSyncedAt: script.storage_synced_at, foolShared } }); }
    if (url.pathname.startsWith('/api/private-scripts/') && url.pathname.endsWith('/storage-sync') && req.method === 'POST') { const user = requireUser(req, res); if (!user) return; const scriptId = decodeURIComponent(url.pathname.slice('/api/private-scripts/'.length, -'/storage-sync'.length)), script = userScript(user, scriptId); if (!script) return json(res, 404, { error: 'Script not found.' }); await syncScriptToNeva(user, scriptId, decrypt(script)); const syncedAt = now(); db.prepare('UPDATE private_scripts SET storage_synced_at=? WHERE id=?').run(syncedAt, scriptId); return json(res, 200, { ok: true, storageSyncedAt: syncedAt }); }
    if (url.pathname.startsWith('/api/private-scripts/') && req.method === 'PUT') { const user = requireUser(req, res); if (!user) return; const scriptId = decodeURIComponent(url.pathname.slice('/api/private-scripts/'.length)), script = userScript(user, scriptId); if (!script) return json(res, 404, { error: 'Script not found.' }); const body = await readBody(req), name = scriptName(body.name), content = String(body.content || ''); if (content.length > 500_000) return json(res, 400, { error: 'Script exceeds the 500 KB limit.' }); const mirrored = !!integrationRow(user, 'neva-storage'); if (mirrored) await syncScriptToNeva(user, scriptId, content); const encrypted = encrypt(content), savedAt = now(); db.prepare('UPDATE private_scripts SET name=?,cipher=?,iv=?,tag=?,updated_at=?,storage_synced_at=? WHERE id=?').run(name, encrypted.body, encrypted.iv, encrypted.tag, savedAt, mirrored ? savedAt : null, scriptId); return json(res, 200, { ok: true, updatedAt: savedAt, storageSyncedAt: mirrored ? savedAt : null }); }
    if (url.pathname.startsWith('/api/private-scripts/') && req.method === 'DELETE') { const user = requireUser(req, res); if (!user) return; const scriptId = decodeURIComponent(url.pathname.slice('/api/private-scripts/'.length)), script = userScript(user, scriptId); if (!script) return json(res, 404, { error: 'Script not found.' }); if (script.storage_synced_at && integrationRow(user, 'neva-storage')) await removeScriptFromNeva(user, scriptId); db.prepare('DELETE FROM private_scripts WHERE id=? AND user_id=?').run(scriptId, user.id); return json(res, 200, { ok: true }); }
    if (url.pathname === '/api/integrations/job-monitor/balance' && req.method === 'GET') { const user = requireUser(req, res); if (!user) return; const data = await providerRead(user, '/external/balance'); return json(res, 200, { points: Number(data.points || 0), thb: Number(data.points || 0) / 100 }); }
    if (url.pathname === '/api/integrations/job-monitor/jobs' && req.method === 'GET') { const user = requireUser(req, res); if (!user) return; return json(res, 200, { jobs: storedJobs(user) }); }
    if (url.pathname === '/api/integrations/job-monitor/jobs' && req.method === 'POST') { const user = requireUser(req, res); if (!user) return; const body = await readBody(req); const jobId = String(body.jobId || '').trim(); if (!/^[A-Za-z0-9_-]{6,100}$/.test(jobId)) return json(res, 400, { error: 'Enter a valid job ID.' }); const job = cleanJob(await providerRead(user, `/external/job/${encodeURIComponent(jobId)}`), jobId); saveJob(user, job); return json(res, 201, { job }); }
    if (url.pathname === '/api/integrations/job-monitor/jobs/sync' && req.method === 'POST') { const user = requireUser(req, res); if (!user) return; const ids = storedJobs(user).slice(0, 40).map(job => job.id); const jobs = []; const errors = []; for (const jobId of ids) { try { const job = cleanJob(await providerRead(user, `/external/job/${encodeURIComponent(jobId)}`), jobId); saveJob(user, job); jobs.push(job); } catch (error) { errors.push({ id: jobId, error: error.message }); } } return json(res, 200, { jobs, errors }); }
    if (url.pathname.startsWith('/api/integrations/job-monitor/jobs/') && url.pathname.endsWith('/accounts') && req.method === 'GET') { const user = requireUser(req, res); if (!user) return; const jobId = decodeURIComponent(url.pathname.slice('/api/integrations/job-monitor/jobs/'.length, -'/accounts'.length)); if (!/^[A-Za-z0-9_-]{6,100}$/.test(jobId)) return json(res, 400, { error: 'Invalid job ID.' }); const data = await providerRead(user, `/external/job/${encodeURIComponent(jobId)}/accounts`); const accounts = Array.isArray(data.accounts) ? data.accounts.map(account => ({ status: String(account.status || 'UNKNOWN') })) : []; return json(res, 200, { counts: accounts.reduce((result, account) => ({ ...result, [account.status]: (result[account.status] || 0) + 1 }), {}), total: accounts.length }); }
    if (url.pathname.startsWith('/api/integrations/job-monitor/jobs/') && req.method === 'GET') { const user = requireUser(req, res); if (!user) return; const jobId = decodeURIComponent(url.pathname.slice('/api/integrations/job-monitor/jobs/'.length)); if (!/^[A-Za-z0-9_-]{6,100}$/.test(jobId)) return json(res, 400, { error: 'Invalid job ID.' }); const job = cleanJob(await providerRead(user, `/external/job/${encodeURIComponent(jobId)}`), jobId); saveJob(user, job); return json(res, 200, { job }); }
    if (url.pathname.startsWith('/api/integrations/job-monitor/jobs/') && req.method === 'DELETE') { const user = requireUser(req, res); if (!user) return; const jobId = decodeURIComponent(url.pathname.slice('/api/integrations/job-monitor/jobs/'.length)); db.prepare('DELETE FROM job_monitor_jobs WHERE user_id=? AND job_id=?').run(user.id, jobId); return json(res, 200, { ok: true }); }
    if (url.pathname === '/api/vault' && req.method === 'GET') { const user = requireUser(req, res); if (!user) return; const row = db.prepare('SELECT * FROM vault_snapshots WHERE user_id=?').get(user.id); if (!row) return json(res, 200, { revision: 0, vault: null }); const vault = JSON.parse(decrypt(row)); return json(res, 200, { revision: row.revision, vault }); }
    if (url.pathname === '/api/vault' && req.method === 'PUT') { const user = requireUser(req, res); if (!user) return; const body = await readBody(req); if (!Array.isArray(body.vault)) return json(res, 400, { error: 'vault must be an array' }); const current = db.prepare('SELECT revision FROM vault_snapshots WHERE user_id=?').get(user.id); const expected = Number(body.baseRevision || 0); if (current && current.revision !== expected) return json(res, 409, { error: 'Vault changed on another device', revision: current.revision }); const encrypted = encrypt(JSON.stringify(body.vault)); const revision = (current?.revision || 0) + 1; db.prepare('INSERT INTO vault_snapshots (user_id,revision,cipher,iv,tag,updated_at) VALUES (?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET revision=excluded.revision,cipher=excluded.cipher,iv=excluded.iv,tag=excluded.tag,updated_at=excluded.updated_at').run(user.id, revision, encrypted.body, encrypted.iv, encrypted.tag, now()); return json(res, 200, { ok: true, revision }); }
    return json(res, 404, { error: 'Not found' });
  } catch (error) { console.error(`[saturnity] ${error.message}`); return json(res, 500, { error: 'Server error' }); }
});
server.listen(port, '127.0.0.1', () => console.log(`Saturnity backend listening on http://127.0.0.1:${port}`));
